# Configuration for cargo-deny
# More detailed docs can be found at https://embarkstudios.github.io/cargo-deny/

# This section is considered when running `cargo deny check bans`.
[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Allow wildcard dependencies
wildcards = "allow"
# The graph highlighting used when creating dotgraphs for crates
highlight = "all"

# This section is considered when running `cargo deny check licenses`.
[licenses]
# Version of the license list to use
version = 2
# The confidence threshold for detecting a license from license text.
confidence-threshold = 0.8

# Allow only these licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "CC0-1.0",
    "MPL-2.0",
    "OpenSSL",
]

# Skip this crate when checking licenses
exceptions = [
    # ring uses multiple licenses
    { allow = ["ISC", "MIT", "OpenSSL"], name = "ring" },
    # webpki uses ISC
    { allow = ["ISC"], name = "webpki" },
]

# This section is considered when running `cargo deny check sources`.
[sources]
# Lint level for what to happen when a crate from a crate registry that is not in the allow list is encountered
unknown-registry = "warn"

# Lint level for what to happen when a crate from a git repository that is not in the allow list is encountered
unknown-git = "warn"

# List of allowed crate registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

# List of allowed Git repositories
allow-git = []

# This section is considered when running `cargo deny check advisories`.
[advisories]
# Version of the advisory database to use
version = 2
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"

# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]

# A list of advisory IDs to ignore
ignore = [
    # Add specific advisory IDs to ignore here if needed
    # Example: "RUSTSEC-2020-0001",
]